name: Deploy Feed Generator to VPS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache target directory
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Build release binary
        run: cargo build --release

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Create remote directory
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
            "mkdir -p /var/www/noreposts-feed"

      - name: Deploy binary and migration
        run: |
          scp -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no \
            target/release/following-no-reposts-feed \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/noreposts-feed/

          scp -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no \
            migrations/001_initial.sql \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/noreposts-feed/

      - name: Deploy .env file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env.production
          echo "PORT=${{ secrets.PORT }}" >> .env.production
          echo "FEEDGEN_HOSTNAME=${{ secrets.FEEDGEN_HOSTNAME }}" >> .env.production
          echo "FEEDGEN_SERVICE_DID=${{ secrets.FEEDGEN_SERVICE_DID }}" >> .env.production
          echo "JETSTREAM_HOSTNAME=${{ secrets.JETSTREAM_HOSTNAME }}" >> .env.production

          scp -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no \
            .env.production \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/var/www/noreposts-feed/.env

      - name: Set permissions
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
            "chmod +x /var/www/noreposts-feed/following-no-reposts-feed"

      - name: Restart service
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
            "systemctl restart noreposts-feed && systemctl status noreposts-feed --no-pager || true"

      - name: Cleanup
        if: always()
        run: |
          rm -f ~/.ssh/deploy_key
          rm -f .env.production
